name: Build Sonic Unleashed iOS
on:
  workflow_dispatch: # This creates the "Run workflow" button

jobs:
  build-ios:
    runs-on: macos-15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # This uses the 'key' you added to your Secrets
          token: ${{ secrets.MY_GITHUB_TOKEN }} 

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable' 

      - name: Install Dependencies
        run: |
          brew update
          brew install freetype pkg-config

      - name: Prepare Build
        run: |
          mkdir -p build
          cd build
          cmake .. -G Xcode \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64
            -DCMAKE_PREFIX_PATH="/opt/homebrew"

      - name: Compile Game Engine
        run: |
          cd build
          xcodebuild -scheme UnleashedRecomp -configuration Release -sdk iphoneos build CODE_SIGNING_ALLOWED=NO

      - name: Package for Sideloading
        run: |
          cd build/Release-iphoneos
          mkdir -p Payload
          cp -r UnleashedRecomp.app Payload/
          zip -r Unleashed.ipa Payload/

      - name: Upload Finished IPA
        uses: actions/upload-artifact@v4
        with:
          name: Unleashed-Mobile-Build
          path: build/Release-iphoneos/Unleashed.ipa
