name: Build Sonic Unleashed iOS
on:
  workflow_dispatch: # This creates the "Run workflow" button

jobs:
  build-ios:
    runs-on: macos-15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # This uses the 'key' you added to your Secrets
          token: ${{ secrets.MY_GITHUB_TOKEN }} 

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable' 

      - name: Install Dependencies
        run: |
          brew update
          brew install freetype pkg-config curl openssl fmt glslang ninja

      - name: Prepare Build
        run: |
          mkdir -p build
          cd build
          cmake .. -G Ninja \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_PREFIX_PATH="/opt/homebrew;/opt/homebrew/opt/curl;/opt/homebrew/opt/openssl;/opt/homebrew/opt/fmt" \
            -DFREETYPE_INCLUDE_DIRS=/opt/homebrew/include/freetype2 \
            -DFREETYPE_LIBRARY=/opt/homebrew/lib/libfreetype.dylib \
            -DCURL_INCLUDE_DIR=/opt/homebrew/opt/curl/include \
            -DCURL_LIBRARY=/opt/homebrew/opt/curl/lib/libcurl.dylib \
            -Dfmt_DIR=/opt/homebrew/opt/fmt/lib/cmake/fmt \
            -DUNLEASHED_RECOMP_IOS_ENABLE_CODE_SIGNING=OFF \
            -DCMAKE_PROGRAM_PATH="/opt/homebrew/bin" \
            -DSH_COMPILER_EXECUTABLE="/opt/homebrew/bin/glslangValidator" 


      - name: Compile Game Engine
        run: |
          cd build
          ninja
          

      - name: Package for Sideloading
        run: |
          cd build/Release-iphoneos
          mkdir -p Payload
          cp -r *.app Payload/ || cp -r Release-iphoneos/*.app Payload/ || true
          zip -r Unleashed.ipa Payload/
          zip -r Unleashed.ipa Payload/

      - name: Upload Finished IPA
        uses: actions/upload-artifact@v4
        with:
          name: Unleashed-Mobile-Build
          path: Unleashed.ipa
